---
sidebar: sidebar 
permalink: learn-builders.html 
keywords: software builders, development, benefits 
summary: Builders용 BlueXP  워크로드 공장은 소프트웨어 구축자를 위한 신속한 구축 환경 생성 툴입니다. 
---
= 구축자를 위한 BlueXP  워크로드 팩토리에 대해 알아보십시오
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Builders용 BlueXP  워크로드 공장은 소프트웨어 구축자를 위한 신속한 구축 환경 생성 툴입니다. 개인 개발 환경을 빠르게 설정하여 시간을 절약하고 개발자를 위한 셀프 서비스를 지원하는 동시에 DevOps 팀에서 인프라에 대한 제어를 유지할 수 있도록 합니다. 소프트웨어 개발자는 Builders를 사용하여 전문 데이터 스토리지를 요구하거나 개발 인프라를 이해하지 않아도 작업 공간을 빠르게 만들 수 있습니다.



== 구축자를 위한 BlueXP  워크로드 팩토리는 무엇입니까?

Builders용 BlueXP  워크로드 공장은 개발자가 여러 버전의 소프트웨어를 관리하고 상호 작용하는 방식을 간소화하도록 설계되었습니다. 빌더들은 Perforce Helix Core와 원활하게 통합되어 소프트웨어 버전의 즉각적인 복제본을 제공하고 개발, QA 및 CI/CD 프로세스를 위한 즉시 사용 가능한 작업 공간을 만듭니다.

Builders를 사용하면 손쉽게 프로젝트를 만들고 소프트웨어 환경과 아티팩트를 나타내는 볼륨을 할당할 수 있습니다. 소프트웨어를 업데이트하면 볼륨의 스냅샷을 생성하여 해당 시점에 소프트웨어 상태를 캡처할 수 있습니다. 즉, 버전 제어 시스템과 다시 동기화하지 않고도 모든 버전의 소프트웨어에 즉시 액세스할 수 있으므로 귀중한 시간과 리소스가 절약됩니다.

Builders는 ONTAP의 스냅샷 및 클론 기능을 활용하여 개발 워크플로우를 개선하고, 여러 버전의 소프트웨어에 빠르게 액세스하고, 개발 주기를 단축하고, 출시 기간을 단축합니다.

작업 부하 공장에 대한 자세한 내용은 을 link:https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html["워크로드 공장 개요"^]참조하십시오.



== 빌더 기능을 위한 BlueXP  워크로드 팩토리

구축자를 위한 BlueXP  워크로드 공장은 다음과 같은 기능을 제공합니다.

* 프로젝트를 만들고, 편집하고, 제거합니다
* 정의된 소프트웨어 버전의 스냅샷을 생성합니다
* 작업 공간 생성 및 삭제(클론 기준)
* 액세스 정책을 만들어 프로젝트에 대한 액세스를 제어합니다
* 각 프로젝트의 용량 사용량을 분석합니다
* 각 프로젝트의 클론 크기 제한 및 클론 보존을 제어합니다
* Perforce와 같은 버전 제어 시스템과 통합됩니다




== 빌더의 프로젝트 및 작업 영역

빌더를 사용할 때 프로젝트를 생성하고 소프트웨어 환경과 아티팩트를 나타내는 볼륨을 할당합니다. 새 버전의 소프트웨어를 생성할 때마다 볼륨 데이터를 다시 동기화하고 프로젝트 스냅샷을 생성하여 볼륨 상태를 알려진 버전으로 표시해야 합니다. 프로젝트 소스 볼륨이 롤링 업데이트를 받고 여러 버전을 표시하기 위한 여러 스냅샷이 있을 수 있습니다. 각 스냅샷을 즉시 개발자, QA 또는 빌드 프로세스에 사용할 수 있는 편집 가능한 전용 저장소 또는 공유 리포지토리로 사용할 수 있습니다. 특정 소프트웨어 버전의 컨텍스트에서 클론은 작업 영역입니다.



== 워크로드 공장 내 운영 모드

세 가지 운영 모드(_basic_,_read_and_automate_)는 워크로드 공장 내부 및 외부에서 배포할 수 있는 유연한 옵션을 제공합니다. 워크로드 공장 외부에서 사용할 코드 조각으로 _BASIC_MODE에 대해 제로 트러스트 상태에서 즉각적인 가치를 얻을 수 있습니다. _READ_AND_AUTOMATE_MODE에서 증분 신뢰를 사용하여 증분 값을 얻습니다.

에 대해 자세히 link:https://docs.netapp.com/us-en/workload-setup-admin/operational-modes.html["워크로드 공장 내 운영 모드"^]알아보십시오.



== 워크로드 팩토리 코드 박스를 통한 자동화

워크로드 공장에서 _Codebox_의 내장된 자동화 기능을 도입했습니다. 코드박스는 다음과 같은 자동화 이점을 제공합니다.

* * 코드 스니펫 생성 *: 리소스 생성 중에 IAC(Infrastructure-as-Code) 스니펫이 생성되므로 기존 오케스트레이션 워크플로우와의 원활한 통합이 가능합니다.
* * 코드형 인프라 공동 파일럿 *: 코드상자는 개발자와 DevOps가 워크로드 공장에서 지원하는 모든 작업을 실행할 수 있도록 코드를 생성하는 코드형 인프라(IAC) 공동 파일럿입니다.
* * 코드 뷰어 및 자동화 카탈로그 *: 코드박스는 자동화를 빠르게 분석할 수 있는 코드 뷰어와 빠른 향후 재사용을 위한 자동화 카탈로그를 제공합니다.




== 비용

워크로드 공장의 빌더 기능을 사용하는 데 비용이 들지 않습니다.



== 라이센싱

NetApp는 워크로드 공장의 빌더 기능을 사용하기 위해 특별한 라이센스가 필요하지 않습니다.



=== 지원 지역

구축자는 FSx for ONTAP가 지원되는 모든 상업 지역에서 지원됩니다. https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["지원되는 아마존 지역을 봅니다."^]

다음 AWS 지역은 지원되지 않습니다.

* 중국 지역
* GovCloud(미국) 지역
* 비밀 클라우드
* 최고 비밀 클라우드




== 도움말 보기

NetApp ONTAP용 Amazon FSx는 AWS 퍼스트 파티 솔루션입니다. 이 서비스를 사용하는 FSx for ONTAP 파일 시스템, 인프라 또는 솔루션과 관련하여 궁금한 사항이나 기술 지원 문제가 있는 경우 AWS 관리 콘솔의 지원 센터를 사용하여 AWS에 지원 케이스를 여십시오. “FSx for ONTAP” 서비스와 적절한 범주를 선택합니다. AWS 지원 케이스를 생성하는 데 필요한 나머지 정보를 제공합니다.

작업 부하 공장 또는 작업 부하 공장 애플리케이션 및 서비스에 대한 일반적인 질문은 을 참조하십시오link:get-help-builders.html["워크로드 공장을 위한 빌더에 대한 도움을 받으십시오"].
