---
settings:
  name: Builders workloads
  platform: cloud
  internal:
    pdf_enabled: true
    termcheck_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  release_notes_autogen:
    release_notes_repo: workload-relnotes
  langs: ko-kr,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,zh-cn,zh-tw
sidebar:
  entries:
  - title: 워크로드 생성기
    url: "/index.html"
  - title: 릴리스 정보
    entries:
    - title: 새로운 소식
      url: "/whats-new.html"
    - title: 알려진 제한 사항
      url: "/known-limitations.html"
  - title: 시작하십시오
    entries:
    - title: 구축자를 위한 BlueXP  워크로드 팩토리에 대해 알아보십시오
      url: "/learn-builders.html"
    - title: 빠른 시작
      url: "/quick-start-builders.html"
    - title: 요구 사항
      url: "/requirements-builders.html"
    - title: 구축자를 Perforce와 통합합니다
      url: "/integrate-perforce.html"
  - title: 빌더 워크로드 사용
    entries:
    - title: 프로젝트를 관리합니다
      url: "/manage-projects.html"
    - title: 작업 영역을 만듭니다
      url: "/create-workspaces.html"
    - title: Codebox로 자동화
      url: "/automate-codebox.html"
  - title: 지식 및 지원
    entries:
    - title: 지원을 위해 등록하십시오
      url: "/support-registration.html"
    - title: 도움을 받으십시오
      url: "/get-help-builders.html"
  - title: 법적 고지
    url: "/legal-notices.html"
product-family:
  name: BlueXP workload factory for AWS
  repo: workload-family
